### PR TITLE
Address typo in CHANGES.adoc

### PR DESCRIPTION
**Pull request by Stargator**
Minor typo fix

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by Stargator** [comment]
@MarkEWaite Does this mean this will be merged in?

**Comment by MarkEWaite** [comment]
> @MarkEWaite Does this mean this will be merged in?

I'm not a maintainer of this plugin.  I can't commit that it will be merged.  If/when #13 is merged, then this pull request will be merged as well because the commit in this pull request is included in #13 .  I didn't want to lose this change when I created #13, so I included that commit in my pull request.  I love `gh pr checkout 9` and `git merge` so that it can combine multiple pull requests.  I hoped that would increase the chance of #13 being merged.

**Comment by Stargator** [comment]
@MarkEWaite Okay, I thought since you approved you had some say. Okay, thank you.

**Comment by MarkEWaite** [comment]
This pull request can be closed now.  A rebased version of this change was included in #13

**Pull request closed without merging**
